-- 2024-03-12: 5F 公募基金升级

-- 2024-06-28 对接 cmdb2
create table ssoc.cmdb2
(
    id                         bigint auto_increment
        primary key,
    inet                       varchar(50) not null,
    app_cluster                longtext    null,
    app_duty                   longtext    null,
    appid                      longtext    null,
    appname                    longtext    null,
    auto_renew                 longtext    null,
    asset_id                   longtext    null,
    asset_status               longtext    null,
    baoleiji_identity          longtext    null,
    beetle_service             longtext    null,
    billing_type               longtext    null,
    brand                      longtext    null,
    business                   longtext    null,
    business_env               longtext    null,
    charge_mode                longtext    null,
    ci_type                    longtext    null,
    cmc_ip                     longtext    null,
    cnc_ip                     longtext    null,
    comment                    longtext    null,
    cost_dep_cas_id            longtext    null,
    cpu                        longtext    null,
    cpu_count                  bigint      null,
    ctc_ip                     longtext    null,
    create_date                longtext    null,
    created_at                 longtext    null,
    created_time               longtext    null,
    deleted                    longtext    null,
    department                 longtext    null,
    description                longtext    null,
    device_spec                longtext    null,
    docker_cpu_count           longtext    null,
    env                        longtext    null,
    exp_date                   longtext    null,
    expired_at                 longtext    null,
    external_id                longtext    null,
    float_ip                   longtext    null,
    harddisk                   longtext    null,
    host_ip                    longtext    null,
    host_type                  longtext    null,
    hostname                   longtext    null,
    host_sn                    longtext    null,
    hyper_threading            longtext    null,
    idc                        longtext    null,
    ilo_ip                     longtext    null,
    image                      longtext    null,
    image_version              longtext    null,
    instance_id                longtext    null,
    ipv6                       longtext    null,
    imported_at                longtext    null,
    in_scaling_group           longtext    null,
    instance_type              longtext    null,
    internet_max_bandwidth_out bigint      null,
    k8s_cluster                longtext    null,
    kernel_version             longtext    null,
    logic_cpu_count            bigint      null,
    minion_not_check           longtext    null,
    name                       longtext    null,
    namespace                  longtext    null,
    net_open                   longtext    null,
    op_duty                    longtext    null,
    op_duty_backup             longtext    null,
    op_duty_main               longtext    null,
    op_duty_standby            longtext    null,
    os_arch                    longtext    null,
    os_type                    longtext    null,
    os_version                 longtext    null,
    power_states               longtext    null,
    private_ip                 longtext    null,
    public_cloud_id            longtext    null,
    public_cloud_idc           longtext    null,
    private_cloud_ip           longtext    null,
    private_cloud_type         longtext    null,
    rack                       longtext    null,
    raid                       longtext    null,
    ram                        longtext    null,
    ram_size                   longtext    null,
    rd_duty_main               longtext    null,
    rd_duty_member             longtext    null,
    region                     longtext    null,
    resource_limits            longtext    null,
    resource_requests          longtext    null,
    security_info              longtext    null,
    server                     longtext    null,
    server_room                longtext    null,
    sn                         longtext    null,
    shutdown_behavior          longtext    null,
    shutdown_mode              longtext    null,
    status                     longtext    null,
    sys_duty                   longtext    null,
    tags                       longtext    null,
    throughput                 bigint      null,
    trade_type                 longtext    null,
    update_time                longtext    null,
    updated_at                 longtext    null,
    `use`                      longtext    null,
    uuid                       longtext    null,
    vcpu_count                 bigint      null,
    vmem_size                  bigint      null,
    vserver_type               longtext    null,
    zabbix_not_check           longtext    null,
    zone                       longtext    null,
    constraint cmdb2_pk
        unique (inet)
);



