### call 61.129.249.67 alert.eastmoney.com
POST http://61.129.249.67/api/v0.1/alerts
Host: alert.eastmoney.com
Content-Type: application/json

{
    "origin_name": "test001",
    "alert_type": "System",
    "alert_object": "cpu",
    "alert_attribute": "load",
    "severity": "middle",
    "subject": "这是一个测试",
    "tags": "hostname=localhost,a=b,c=d",
    "notifier": "[{\"name\":\"张三\",\"mobile\":\"15927458888\",\"email\":\"zhangsan@eastmoney.com\",\"serial_number\":\"160001\",\"notify_methods\":\"weixin,sms\"}]"
}
