# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: 编译构建

on:
  workflow_dispatch:
  push:
    branches:
      - v2

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        goos:
          - linux
          - windows
          - darwin
        goarch:
          - amd64
          - arm64
        exclude:
          - goos: windows
            goarch: arm64   # 排除不用的组合

    steps:
      - name: 检出代码
        uses: actions/checkout@v6

      - name: 安装 Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.26.0-rc.2 # https://github.com/actions/setup-go?tab=readme-ov-file#pre-release-versions
          # go-version-file: go.mod
          # check-latest: true

      - name: 编译程序
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 0
        run: sh build.sh

      - name: 生成打包时间
        run: echo "BUILD_DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: 上传产物
        uses: actions/upload-artifact@v5
        with:
          name: ssoc-manager_${{ matrix.goos }}-${{ matrix.goarch }}_${{ env.BUILD_DATE }}
          path: |
            ssoc-manager_*
