# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: 编译 Linux 版本

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: 安装 Go SDK
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: 编译代码
      run: sh build.sh
    
    - name: 下载文件
      uses: actions/upload-artifact@v4.6.1
      with:
        name: vela-manager
        path: vela-manager-*
